spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/hedu?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: password
    pool:
      enabled: true
      max-size: 10
      initial-size: 10
      validation-query: select 1
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 10
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
    client-type: lettuce
  jackson:
    default-property-inclusion: non_null
  main:
    web-application-type: reactive

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

